### ISSUE TITLE
example for grpc

### ISSUE THREAD

**Issue by viktortnk** [trueaccord/scalapb-pants#1]
Hi, I tried to configure this plugin for grpc. I assume protoc3 is required

Got following error when using config

```
[gen.scalapb-gen]
protoc_version: '3.0.0'
```

Any plans to continue supporting this plugin?
Thanks

```
                       ==== stderr ====
                       Unknown flag: -v

                       ==== stdout ====
                       protoc-jar: protoc version: 300, detected platform: mac os x/x86_64
                       protoc-jar: executing: [/var/folders/ty/tzry86q94kd8rswsyps4bthw0000gp/T/protoc4906303607732363571.exe, -v'3.0.0', --plugin=protoc-gen-scala=/var/folders/ty/tzry86q94kd8rswsyps4bthw0000gp/T/protocbridge8992074608527053658, --scala_out=java_conversions,grpc:/Users/viktortnk/whisk/skyline/.pants.d/gen/scalapb-gen/252d64521cf9/src.protobuf.simple.simple_proto/current, --java_out=/Users/viktortnk/whisk/skyline/.pants.d/gen/scalapb-gen/252d64521cf9/src.protobuf.simple.simple_proto/current, --proto_path=src/protobuf, src/protobuf/simple/./simple.proto]

17:28:14 00:01       [execute]
FAILURE: scalapb-gen ... exited non-zero (1)


17:28:14 00:01   [complete]
```

**Comment by thesamet** [comment]
Yes, I am aiming to keep supporting this. I think that ther protoc_version is being passed as is to protoc-jar, so maybe try `protoc_version: 300`. I'll give it a closer look later.

**Comment by omrihq** [comment]
Any updates on this? Trying to get it going with gRPC right now as well

**Comment by viktortnk** [comment]
we use following snippet in pants.ini

```
[gen.scalapb-gen]
protoc_version: 320
```

**Comment by thesamet** [comment]
@omrihq can you try and report if this works for you?

**Comment by omrihq** [comment]
I'm still not sure how this works. I have `./pants run` working but otherwise I'm still not sure how to run the files themselves and generate the scalapb-made proto files.

**Comment by thesamet** [comment]
I'll take a look and set up an example repo with grpc.

**Comment by omrihq** [comment]
That would be incredible, thank you

**Comment by omrihq** [comment]
Any updates on this?

**Comment by thesamet** [comment]
Check out this repository for a barebones example: https://github.com/scalapb/scalapb-pants-example

**Comment by omrihq** [comment]
תודה רבה
