### ISSUE TITLE
New release with latest fixes?

### ISSUE THREAD

**Issue by cyburgee** [trueaccord/scalapb-pants#10]
Hello, are you planning to publish a release with the fixes for `sources_globs` and `fatal_warnings`?

**Comment by davydkov** [comment]
I'm raising the same question. Can you publish a new release?

**Comment by thesamet** [comment]
Sure thing, will cut a release in the next few days.

**Comment by thesamet** [comment]
Released scalapb-pants 0.3.0 and updated the example project at https://github.com/scalapb/scalapb-pants-example
