### ISSUE TITLE
How to Generate Scala for Protos from 3rd Party Jar

### ISSUE THREAD

**Issue by cyburgee** [trueaccord/scalapb-pants#11]
Hello, it's unclear to me how to generate scala for protobuf files included in another jar when using pants. I see instructions for sbt here: https://scalapb.github.io/faq.html

I've tried with a 3rdparty/BUILD file including:
```
jar_library(name='proto-google-cloud-vision-v1',
            jars=[
                jar(org='com.google.api.grpc', name='proto-google-cloud-vision-v1', rev='1.68.0')
            ])
```
and in my example/BUILD:
```
scalapb_library(
    name='example',
    sources=globs('*.proto'),
    dependencies=[
        '3rdparty/jvm/2.12:scalapb-runtime',
        '3rdparty/jvm/2.12:scalapb-runtime-grpc',
        '3rdparty/jvm:proto-google-cloud-vision-v1',
    ],
    imports=[
        '3rdparty/jvm/2.12:scalapb-runtime',
        '3rdparty/jvm:proto-google-cloud-vision-v1',
    ],
)
```
but upon compilation i see errors from pants like the following:
```
[error]... object web_detection is not a member of package com.google.cloud.vision.v1
[error] com.google.cloud.vision.v1.web_detection.WebDetectionProto
```

Any help would be greatly appreciated.

**Comment by thesamet** [comment]
Hi @cyburgee , this functionality is not implemented in scalapb-pants as far as I can remember. PR will be welcome.

**Comment by cyburgee** [comment]
thanks @thesamet. do you have any pointers as to where I should look? I'm not at all familiar with building pants plugins. After puzzling over the code for a bit would it have something to do with incorporating the `target.payload.imports` into `_calculate_source_roots()`? just taking a stab here.

**Comment by thesamet** [comment]
There is a pants builtin call "unpacked_jar", see https://github.com/pantsbuild/pants/blob/master/examples/src/protobuf/org/pantsbuild/example/unpacked_jars/BUILD that you can see if you can leverage. With some lack no coding is required. From there, you can involve the pants developer community to ask for guidance.
In case you are able to use unpacked_jar, please post it here!

**Comment by cyburgee** [comment]
I was able to use `unpacked_jars` in conjunction with `remote_sources`. thanks for the tip!

**Comment by notxcain** [comment]
In case someone needs and example. It's not obvious from docs at all. I spent ~4 hours researching and fighting Pants 😄 
Put that in your `3rdparty/io/grpc/BUILD`:
```python
jar_library(
    name='services-jar',
    jars=s
        jar('io.grpc', 'grpc-services', '1.31.0')
    ])

unpacked_jars(
    name = 'unpacked-services-jar',
    include_patterns = ['grpc/health/v1/*.proto'],  # Only compile what's needed
    libraries=[':services-jar'],
    intransitive=True # We don't need sources of the dependencies
)

remote_sources(
    name='services',
    sources_target = ':unpacked-services-jar',
    dependencies=[
        '3rdparty:scala-pb',
        '3rdparty/com/thesamet/scalapb/zio-grpc:zio-grpc'
    ],
    dest = scalapb_library
)
```

Then in your project module add dependency on `3rdparty/io/grpc:services`.
