### ISSUE TITLE
Using scalapb/zio-grpc

### ISSUE THREAD

**Issue by OlafurD** [trueaccord/scalapb-pants#13]
I've got a local version of scalapb-pants on my machine, and i'm trying to configure it to also generate code for zio with the zio-grpc code generator. Could someone help me out?

I've modified the `scalapb_gen.py` file to include the plugin as an argument to scalaPBC:

`args.append('--plugin=scalapb.zio_grpc.ZioCodeGenerator')`
`args.append('--zio_out={0}'.format(target_workdir))`

but when I try to compile I get the following error:
```
==== stderr ====
protoc-gen-zio: program not found or is not executable
--zio_out: protoc-gen-zio: Plugin failed with status code 1.
```

**Comment by thesamet** [comment]
Hi @OlafurD ,
See the arguments needed for zio grpc here: https://scalapb.github.io/scalapbc.html#loading-additional-generators-from-maven

Make sure you are using a recent scalapbc

**Comment by OlafurD** [comment]
Thanks

I've updated my version of scalapbc to 0.10.1 and followed the examples for adding additional generators from maven

Now the code generation works, but the generated code does not compile:

`object zio is not a member of package <root>`

I've added the ZIO library to the classpath for the pants plugin, in BUILD.tools:
```
jar_library(name = 'scalapbc',
            jars = [
              scala_jar('com.thesamet.scalapb', 'scalapbc', '0.10.1'),              
              scala_jar(name = 'zio', org = 'dev.zio', rev = '1.0.0-RC18-2'),
            ])
```

**Comment by thesamet** [comment]
You also need [zio-grpc-core](https://mvnrepository.com/artifact/com.thesamet.scalapb.zio-grpc/zio-grpc-core).

**Comment by OlafurD** [comment]
Beautiful, it works now. Thanks so much :)
